### ISSUE TITLE
Lines WAAAAY to long in linear/logistic regressor

### ISSUE THREAD

**Issue by RileyPaddock** [C0BBL3/machine-learning#12]
In Logistic regressor your self.ratings line needs to be broken down, it is impossible to follow
In your linear regressor, while putting your entire evaluate function on 1 line may seem cool, It is like 3 times as long as it should be. That line severely needs to be broken down.

**Comment by C0BBL3** [comment]
1 the logistic regressor thing I am not doing because of the memes and also it would be much more of a pain to undo the mess that is line 9 than it is to read it. Also for the evaluation function, I kinda forgot how to do create an embedded dictionary without dictionary comprehensions.

**Comment by C0BBL3** [comment]
fixed
