### ISSUE TITLE
Decision tree functions should only do 1 thing

### ISSUE THREAD

**Issue by eoriont** [C0BBL3/machine-learning#14]
Currently, in your `decision_tree.py` file, you have a lot of functions that do multiple things depending on which input is `None`. It is generally a better practice to keep a nil value out of your parameters so you don't check for nil later. This can get tangled up with actual form validation (or the like) and you will eventually have to redo it. The two functions `get_low_split` and `get_high_split` do what looks like a very similar thing with slightly different outputs. You should find a way to make fewer function calls to achieve what you're trying to do.

- Combine `goodness_of_split_function`, `get_low_split`, and `get_high_split` into 1 or 2 functions that are shorter

**Comment by C0BBL3** [comment]
fixed
