### ISSUE TITLE
Over complicated filter_columns

### ISSUE THREAD

**Issue by DrM00G** [C0BBL3/machine-learning#3]
I literally just made a new data frame with different column orders which when shorter did the trick, you don't need to transpose and stuff. Actually, the more I look at this class, the more I realize how over coded it is. You may have a reason for this, but I recommend you simplify.

**Comment by C0BBL3** [comment]
you have the transpose it because its filter columns and not filter rows, also its a lot easier to generate a row and transpose it then it is to generate columns alone.

**Comment by C0BBL3** [comment]
fixed
