### ISSUE TITLE
Dataframe functionality(dummy variables)

### ISSUE THREAD

**Issue by RileyPaddock** [C0BBL3/machine-learning#6]
The code in your 2 dummy variable functions is really nice and clean but you shouldn't be picking columns or having multiple functions. You should have 1 function that breaks all the columns with string based entries into their dummy columns.

**Comment by C0BBL3** [comment]
the 1 function would be doing too much, it would be getting the unique dummy columns and adding them to the dictionary, its also better to have many small functions than a small amount of big function.
