### ISSUE TITLE
Linear Regressor Max Value

### ISSUE THREAD

**Issue by geomeza** [C0BBL3/machine-learning#7]
Your linear regressor does not need a max value attribute, I get its there because of the inheritance from your logistic regressor but this is a really simple fix of removing the attribute from the linear one, keeping it in the logistic regressor and when you pass the logistic super().__init__ function just dont pass the max value attribute there, its a simple fix

**Comment by C0BBL3** [comment]
that's to get rid of errors in logistic regression in linear regressor

**Comment by C0BBL3** [comment]
imma try to fix it now tho

**Comment by C0BBL3** [comment]
got rid of a couple of instances but I can't get rid of it entirely for the reason given in the first response.

**Comment by C0BBL3** [comment]
fixed it
